name: flutter_application_1
description: Portable Expense Management Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  
  # Security
  flutter_secure_storage: ^9.0.0
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true